### ISSUE TITLE
Names of the car models of each team

### ISSUE THREAD

**Issue by cappee** [couscous/formulaone-database#1]
A json file like that:
- 2000
  - Ferrari: F2000
  - McLaren: MP4/15
  - Jordan: EJ10
  - Jaguar: R1
  - Williams: FW22
  - Benetton: B200
  - Prost: AP03
  - Sauber: C19
  - Arrows: A21
  - Minardi: M02
  - BAR: 002

**Comment by simo501** [comment]
qg sei pazzo hahahahahaha

**Comment by simo501** [comment]
però se può fa

**Comment by simo501** [comment]
messo
